// <auto-generated />
namespace Climbing.Info.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddLatitudLongitud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLatitudLongitud));
        
        string IMigrationMetadata.Id
        {
            get { return "201807162046511_AddLatitudLongitud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
